# Generated by Django 4.2.5 on 2023-11-13 07:12

import RentRide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentRide', '0002_cardealer_customer_location_order_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to=RentRide.models.custom_image_filename, validators=[RentRide.models.validate_car_image]),
        ),
    ]
